### PR TITLE
Center board

### PR DESCRIPTION
**Pull request by nevtay**
## CHANGES
**script.js**
- Add variable to store board's "offsetLeft" value and apply it to "ontouchmove" event listener

***style.css***
- Add css to center input options and board

### CODE REVIEW

**Review by enwee — COMMENTED** [review]
`document.getElementById('board')` is unnecessary. html elements with #id can be used directly in script by their #id names. i would just directly use it as `board.offsetLeft`. 
Although it is prob NOT good but i think its ok for a simple personal project.

**Review by enwee — COMMENTED** [review]
The program handles any image aspect ratio, and with the CSS set `margin: auto`, have to consider if `board.offsetTop` has to be accounted for as well, since targeted devices also have varying aspec ratios and orientation portrait/landscape.

**Review by enwee — COMMENTED** [review]
`margin: auto`, consider if `board.offsetTop` has to be factored in

**Review by enwee — COMMENTED** [review]
`board.offsetLeft` is quite well self describing. would not create a function to get it.
`getLeftOffsetValue("board")` does not read much different from `board.offsetLeft`

**Comment by enwee** [comment]
Hi @Nev, 

let me see if i "use" the intent of a pull request correctly.  I think i will not be incoporating the board and text centering changes as i think there are other parts/logic in program that also makes the assumption of no offset from (0,0). Also, i've written the pieces scattering function to scatter to right and bottom edge of board. I prefer it like this for now as it fits my own tablet that i use for playing the game well.
But i've learnt from you how to get the offset. perhas, my choice of using pageX, pageY might not be the best choice for centered components. There are others, (e.g. clientX, etc) that might be directly usable without needing to account for offset.

**Comment by nevtay** [comment]
Hey @enwee, I definitely should have seen and factored in `offsetTop` as well, and you raised an important reminder with respect to why `document.getElementById` is unnecessary in this case. And it's nice to know that you're getting a lot of fun out of your project!

**Comment by enwee** [comment]
@nevtay but I have taken your point and included `board.offsetLeft` and `board.offsetTop` which i previously did not think of and it indeed is a bug. I might center the stuff in future as and when while i am still adding tweaks here and there.

**Pull request closed without merging**
